.\" json2bash. convert JSON data to bash-friendly variable declarations.
.\" Contact sean@crazyhorsecoding.com to correct errors or typos.
.TH man 8 "06 Jan 2017" "1.0" "json2bash man page"
.SH NAME
json2bash - convert JSON data to bash-friendly variable declarations.
.SH SYNOPSIS
json2bash [options] [jsonData]
.SH DESCRIPTION
json2bash can be piped or invoked interactively. it accepts JSON-formatted data on stdin or via it's first param.
.SH OPTIONS
--output-format ( export, declare, on oneLine )
.SH SEE ALSO
node(1) json(1) bash(2)
.SH BUGS
https://gitlab.com/code_monk/json2bash/issues
.SH AUTHOR
Sean Macdonald <sean@crazyhorsecoding.com>